language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: HwRNhqkB1AUJjUlNL2I1NN8t5ywdWl0D1UNPxLP5oztYxKFEqK35rAVALTDGRAewGyFQEWQhtAXMc6R+ERYdSg062C378yO5zCae3834iv8FW3a6YJe1DiKASPdDeY0m4/JVdN6HBt1Py3gM7NiKnUwX4zhHpA8ZTOEp2Msj5QPLmnB1y9RuChwqOWcviIuPx3tT7CSyjMfhY7IN0HhrZSP52tOjF7L+gtWzKRE5CElKH5Zcpf413XfEVxS9Q0zTHbjkC/KmM3NjOhhakGNH9J6eTg7552KsSYOlTC6TGMW4YTZ5wKakwmWSZVr/IWoAhDNMIYvcHrVDBkogGPZwIL5pIC5CLDxIGvQwqNna8xl/gn4G6W88FZUihDLmbN+09M77wMuG8OWxzHaYfu9QdBz1xaG8L0J/mqW/k+JHB0+tpJgjiWZB3zpjkNr5v/f+HmiPsCwsP/2cDw/J5Bhchl8GN3wvnt/hm5ghZtHZ3CAJYjTCq5e2watt90mTcBYlxOTuo5al0P7AC0HMrXivrv5gGV7ZYEj8eIHf0RH3MCmMiq+rRYikItxkcCULDKia7bshz8tnoCnwm0VtpxJpjSDv43lQCJk24VjICOX8FM5c6MDhrMTfCHR1lgf1BxHaD712RPQErBXgRh0Izsgs/6JlWF9HNHYOjPT9PKFzx6c=
