language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: guarded-anchorage-26538
  api_key:
    secure: XaTdsRupRFIMgF4wa5BWEAOI8Ki46d+49hmj6QZfNhAgucYohRP3oXp7IZhnGJIkl6rtdSEODFlY3PbwNV5rp15IM+PmXd0ysTXNC5zS2Zpa2KLRrF05ElsD+Sycc3/RB6gzfuiOlpB42+LJRWEJZigcUUtiUGDqei6JjDsad8miGSKquCSXgtB3V8P/xl1S2efFpqi69FEhFiNnOeGyf2JuhqADJHleC4QKL0IP9Pf8MuaL7+PSXK5NeC3P7tt2oSu9tieByq1RdTgDhYyaHcc82qw9bAmvFzbm+M1HtMfneTNRcMdifzC/dZs5mUnyFJX+XQ2UmgnCUObjY4UnyyA6KadMC3u0/OsPErz5GW4d1LXfIw2V/XaYl4IRSaDr/7z83OdA9CgGh7r5vPyG7TxQe3Z7jGK7Gqn/cmc2SYIf/VrB3xwMpVWexH35tzxFRLPyz+tp5VTmcs521dQFkchgoDPRPuLa4oWo4pC9qdFdPmCQsKMktqQcOlsCK6VwwHsLFQMp3P1tJHIIB/DjbPXTAljLR2KgHtNY6Dn4M/HhYjBhYNBGRrM9HB0swXZ1/N5xgX/SuxZrmOvRxcfMRHlTm8eEgqfddVxE6M4lvvSUez+naGajKXQEy/tO7qwbYhcq8884l39t4BorEwDiKpivmu632nGn95oBl02ZTZ4=
